/**
 * Legal Document Wizard Component
 *
 * Generates legal documents:
 * - Template selection
 * - Field input
 * - Preview and download
 */

'use client';

import { useState, useEffect } from 'react';
import {
  FileText,
  Download,
  ChevronRight,
  Check,
  RefreshCw,
  AlertTriangle,
} from 'lucide-react';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import Input from '@/components/ui/Input';
import { showToast } from '@/components/ui/ToastContainer';
import api from '@/lib/api';

interface TemplateField {
  name: string;
  label: string;
  type: 'text' | 'date' | 'textarea';
  required: boolean;
}

interface Template {
  id: string;
  name: string;
  description: string;
  fields: TemplateField[];
}

interface LegalDocumentWizardProps {
  switchId?: string;
  onClose?: () => void;
}

export default function LegalDocumentWizard({
  switchId,
  onClose,
}: LegalDocumentWizardProps) {
  const [step, setStep] = useState<'select' | 'fields' | 'preview'>('select');
  const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(null);
  const [fieldValues, setFieldValues] = useState<Record<string, string>>({});
  const [generating, setGenerating] = useState(false);
  const [generatedDocument, setGeneratedDocument] = useState<{
    documentId: string;
    content: any;
  } | null>(null);

  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    try {
      const response = await api.get('/api/legal/templates');
      setTemplates(response.data.data.templates);
    } catch (error) {
      console.error('Failed to fetch templates:', error);
      showToast('Failed to load templates', 'error');
    } finally {
      setLoading(false);
    }
  };

  const selectTemplate = (template: Template) => {
    setSelectedTemplate(template);
    setFieldValues({});
    setStep('fields');
  };

  const updateField = (name: string, value: string) => {
    setFieldValues({ ...fieldValues, [name]: value });
  };

  const validateFields = (): boolean => {
    if (!selectedTemplate) return false;

    for (const field of selectedTemplate.fields) {
      if (field.required && !fieldValues[field.name]?.trim()) {
        showToast(`${field.label} is required`, 'error');
        return false;
      }
    }
    return true;
  };

  const generateDocument = async () => {
    if (!validateFields()) return;

    setGenerating(true);
    try {
      const response = await api.post('/api/legal/documents/generate', {
        templateId: selectedTemplate!.id,
        switchId,
        fields: fieldValues,
      });

      setGeneratedDocument({
        documentId: response.data.data.documentId,
        content: response.data.data.content,
      });
      setStep('preview');
      showToast('Document generated', 'success');
    } catch (error: any) {
      showToast(
        error.response?.data?.message || 'Failed to generate document',
        'error'
      );
    } finally {
      setGenerating(false);
    }
  };

  const downloadAsPdf = () => {
    if (!generatedDocument) return;

    // Create a simple text version for download
    // In production, you'd generate a proper PDF
    const content = generatedDocument.content;
    const textContent = `
${content.template.name}
Generated: ${new Date(content.generatedAt).toLocaleString()}

${Object.entries(content.fields || {})
  .map(([key, value]) => `${key}: ${value}`)
  .join('\n')}

${content.switchData ? `
Switch: ${content.switchData.title}
Status: ${content.switchData.status}
Created: ${new Date(content.switchData.createdAt).toLocaleString()}
` : ''}

${content.recipients?.length ? `
Recipients:
${content.recipients.map((r: any) => `- ${r.name || r.email}`).join('\n')}
` : ''}

${content.guardians?.length ? `
Guardians:
${content.guardians.map((g: any) => `- ${g.npub.substring(0, 20)}... (${g.type})`).join('\n')}
` : ''}

---
Generated by EchoLock
    `.trim();

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${content.template.name.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showToast('Document downloaded', 'success');
  };

  if (loading) {
    return (
      <Card>
        <div className="flex items-center justify-center py-8">
          <RefreshCw className="w-6 h-6 animate-spin text-black/50" />
          <span className="ml-2 text-black/70">Loading templates...</span>
        </div>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      {/* Step 1: Select Template */}
      {step === 'select' && (
        <>
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5" />
            <h3 className="text-lg font-bold uppercase">Generate Legal Document</h3>
          </div>

          <p className="text-sm text-black/70 mb-4">
            Select a template to generate a legal document for your records.
          </p>

          <div className="space-y-3">
            {templates.map((template) => (
              <div
                key={template.id}
                onClick={() => selectTemplate(template)}
                className="cursor-pointer"
              >
                <Card className="hover:bg-blue transition-colors">
                  <div className="flex items-center justify-between">
                    <div>
                      <h4 className="font-bold">{template.name}</h4>
                      <p className="text-sm text-black/70">{template.description}</p>
                    </div>
                    <ChevronRight className="w-5 h-5 text-black/50" />
                  </div>
                </Card>
              </div>
            ))}
          </div>

          {onClose && (
            <Button variant="secondary" onClick={onClose}>
              Cancel
            </Button>
          )}
        </>
      )}

      {/* Step 2: Fill Fields */}
      {step === 'fields' && selectedTemplate && (
        <>
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5" />
            <h3 className="text-lg font-bold uppercase">{selectedTemplate.name}</h3>
          </div>

          <Card>
            <p className="text-sm text-black/70 mb-4">
              {selectedTemplate.description}
            </p>

            <div className="space-y-4">
              {selectedTemplate.fields.map((field) => (
                <div key={field.name}>
                  {field.type === 'textarea' ? (
                    <div>
                      <label className="block text-sm font-bold mb-1">
                        {field.label}
                        {field.required && (
                          <span className="text-red-500 ml-1">*</span>
                        )}
                      </label>
                      <textarea
                        value={fieldValues[field.name] || ''}
                        onChange={(e) => updateField(field.name, e.target.value)}
                        rows={4}
                        className="w-full px-3 py-2 border-2 border-black rounded resize-none"
                      />
                    </div>
                  ) : (
                    <Input
                      label={field.label + (field.required ? ' *' : '')}
                      type={field.type}
                      value={fieldValues[field.name] || ''}
                      onChange={(e) => updateField(field.name, e.target.value)}
                    />
                  )}
                </div>
              ))}
            </div>

            {switchId && (
              <div className="mt-4 p-3 bg-blue rounded">
                <p className="text-sm text-black/70">
                  <Check className="w-4 h-4 inline mr-1 text-emerald-500" />
                  Switch data will be included automatically
                </p>
              </div>
            )}
          </Card>

          <div className="flex gap-2">
            <Button onClick={generateDocument} disabled={generating}>
              {generating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4 mr-2" />
                  Generate Document
                </>
              )}
            </Button>
            <Button variant="secondary" onClick={() => setStep('select')}>
              Back
            </Button>
          </div>
        </>
      )}

      {/* Step 3: Preview & Download */}
      {step === 'preview' && generatedDocument && (
        <>
          <div className="flex items-center gap-2 mb-4">
            <Check className="w-5 h-5 text-emerald-500" />
            <h3 className="text-lg font-bold uppercase">Document Ready</h3>
          </div>

          <Card className="bg-emerald-50 border-emerald-200">
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-emerald-100 rounded-full">
                <FileText className="w-6 h-6 text-emerald-600" />
              </div>
              <div>
                <p className="font-bold text-emerald-800">
                  {generatedDocument.content.template.name}
                </p>
                <p className="text-sm text-emerald-600">
                  Generated {new Date(generatedDocument.content.generatedAt).toLocaleString()}
                </p>
              </div>
            </div>

            <div className="bg-white rounded p-4 mb-4 max-h-64 overflow-y-auto">
              <h4 className="font-bold mb-2">Document Preview</h4>

              {Object.entries(generatedDocument.content.fields || {}).map(
                ([key, value]) => (
                  <div key={key} className="mb-2">
                    <span className="text-sm text-black/70">{key}:</span>
                    <span className="ml-2 font-medium">{value as string}</span>
                  </div>
                )
              )}

              {generatedDocument.content.switchData && (
                <div className="mt-4 pt-4 border-t">
                  <h5 className="font-bold mb-2">Switch Information</h5>
                  <p className="text-sm">
                    Title: {generatedDocument.content.switchData.title}
                  </p>
                  <p className="text-sm">
                    Status: {generatedDocument.content.switchData.status}
                  </p>
                </div>
              )}

              {generatedDocument.content.recipients?.length > 0 && (
                <div className="mt-4 pt-4 border-t">
                  <h5 className="font-bold mb-2">Recipients</h5>
                  {generatedDocument.content.recipients.map((r: any, i: number) => (
                    <p key={i} className="text-sm">
                      {r.name || r.email}
                    </p>
                  ))}
                </div>
              )}
            </div>

            <Button onClick={downloadAsPdf} className="w-full">
              <Download className="w-4 h-4 mr-2" />
              Download Document
            </Button>
          </Card>

          <div className="p-3 bg-amber-50 border border-amber-200 rounded flex items-start gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-amber-700">
              This document is for informational purposes. For legal validity,
              consult with an attorney in your jurisdiction.
            </p>
          </div>

          <div className="flex gap-2">
            {onClose && <Button onClick={onClose}>Done</Button>}
            <Button
              variant="secondary"
              onClick={() => {
                setGeneratedDocument(null);
                setStep('select');
              }}
            >
              Generate Another
            </Button>
          </div>
        </>
      )}
    </div>
  );
}
