blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/1e9c9h9o/echolock/security/advisories/new
    about: Report a security vulnerability privately (DO NOT open a public issue)
  - name: Discussion Forum
    url: https://github.com/1e9c9h9o/echolock/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Policy
    url: https://github.com/1e9c9h9o/echolock/blob/main/SECURITY.md
    about: Read our security policy and responsible disclosure guidelines
