name: Documentation Improvement
description: Report missing, unclear, or incorrect documentation
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve ECHOLOCK's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - API documentation
        - Code comments
        - Architecture docs
        - Security documentation
        - Contributing guide
        - Setup/Installation guide
        - Tutorial/How-to
        - Roadmap
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: File path or URL of the documentation
      placeholder: docs/ARCHITECTURE.md or https://github.com/1e9c9h9o/echolock/...

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of issue is this?
      options:
        - Missing documentation
        - Unclear/confusing documentation
        - Incorrect/outdated documentation
        - Typo/grammar error
        - Broken link
        - Code example doesn't work
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: The documentation is unclear because...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: It should explain...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context
      placeholder: Additional information...
